# Generated by Django 5.2.1 on 2025-11-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='long_desc',
            field=models.TextField(null=True),
        ),
    ]
