# Generated by Django 5.2.1 on 2025-11-25 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_postmodel_long_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='long_desc',
        ),
    ]
