# Generated by Django 5.2.1 on 2025-11-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_postmodel_long_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
