# Generated by Django 5.2.1 on 2025-12-03 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categorymodel'),
        ),
    ]
